FIXUP: FROMLIST: drm/bridge: anx7625: Add anx7625 MIPI DSI/DPI to DP bridge driver
0day reports:

drivers/gpu/drm/bridge/analogix/anx7625.c: In function 'anx7625_i2c_probe':
drivers/gpu/drm/bridge/analogix/anx7625.c:1970:19: error:
	'struct drm_bridge' has no member named 'of_node'

of_node is conditional on CONFIG_OF, so we can not use IS_ENABLED
to access it conditionally.

BUG=b:140132295,b:143331916
TEST=build

Change-Id: I6af11b240af21e7ba5cd9a8e7af2c5121372a6dc
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2036236
Commit-Queue: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Xin Ji <xji@analogixsemi.com>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>