BACKPORT: FROMGIT: platform/chrome: cros_ec_typec: Add a dependency on USB_ROLE_SWITCH
As reported by the kernel test robot the cros_ec_typec driver fails to
build if the USB_ROLE_SWITCH is not selected, to fix that, add a
dependency on that symbol. This fixes the following build error:

   drivers/platform/chrome/cros_ec_typec.c:133: undefined reference to `usb_role_switch_put'
   ld: drivers/platform/chrome/cros_ec_typec.o: in function `cros_typec_get_switch_handles':
   drivers/platform/chrome/cros_ec_typec.c:108: undefined reference to `fwnode_usb_role_switch_get'
   ld: drivers/platform/chrome/cros_ec_typec.c:117: undefined reference to `usb_role_switch_put'

BUG=None
TEST=Build and boot volteer with CROS_EC_TYPEC enabled, ensure build
compiles successfully and the driver loads on boot.

Fixes: 7e7def15fa4b ("platform/chrome: cros_ec_typec: Add USB mux control")
Reported-by: kernel test robot <lkp@intel.com>
Acked-by: Prashant Malani <pmalani@chromium.org>
Signed-off-by: Enric Balletbo i Serra <enric.balletbo@collabora.com>
(cherry picked from commit bdc4094591c3809e53eb7792344248bb447768c3 git://git.kernel.org/pub/scm/linux/kernel/git/chrome-platform/linux.git for-next)
Signed-off-by: Prashant Malani <pmalani@chromium.org>
Change-Id: I5e849032bb16b5c04d436f60b28dda7828e8f329
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2282998
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Alex Levin <levinale@google.com>