FROMGIT: ASoC: Documentation: fix reference to renamed source file
sound/soc/soc-io.c was merged into sound/soc/soc-component.c, so fixup
the Documentation to use the updated file name.

Error: Cannot open file ../sound/soc/soc-io.c
WARNING: kernel-doc '../scripts/kernel-doc -rst -enable-lineno ../sound/soc/soc-io.c' failed with return code 1

Fixes: 460b42d162e3 ("ASoC: soc-component: merge soc-io.c into soc-component.c")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Acked-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Cc: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Cc: Mark Brown <broonie@kernel.org>
Link: https://lore.kernel.org/r/a9f59f30-8cf2-ea82-567c-1706fd64fe62@infradead.org
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 4946cd45ef665d99074796fdd8ce04ba37ce1bdf
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

BUG=b:161530390
TEST=check audio on lazor

Signed-off-by: Cheng-Yi Chiang <cychiang@chromium.org>
Change-Id: I7aa1e64fba71ea1973a2cb2311546d7d2c9891ec
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2328431
Reviewed-by: Sean Paul <seanpaul@chromium.org>