FIXUP: CHROMIUM: hardlockup: detect hard lockups without NMIs using secondary cpus
s390 builds fail with lots of

panic.c:(.text+0x40a): undefined reference to `touch_softlockup_watchdog'
panic.c:(.text+0x474): undefined reference to `touch_softlockup_watchdog'

SOFTLOCKUP_DETECTOR enables LOCKUP_DETECTOR, but LOCKUP_DETECTOR
is not supported on S390, so SOFTLOCKUP_DETECTOR must not be enabled
on S390 builds. On top of that, the buddy CPU code depends other code
only available if LOCKUP_DETECTOR is enabled, such as the hardlockup_panic
variable. To fix the problem, mark HARDLOCKUP_DETECTOR_BUDDY_CPU as
depending on !S390.

BUG=chromium:941638
TEST=Build s390:allmodconfig

Change-Id: I48c2fdf4e9f2c35f33cfa0c083107ac5886f1593
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1680852
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>
(cherry picked from commit 7c966453ee85056944208a7f73c800b608c06b15)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1984838